version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: my_shop
      POSTGRES_USER: jafar
      POSTGRES_PASSWORD: qwerty25
    ports:
      - "5432:5432"