# Generated by Django 6.0.6 on 2026-07-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Відображення специфікації'),
        ),
    ]
