# Generated by Django 6.0.6 on 2026-07-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productspecification_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
    ]
